preciosa/api/urls.py
# -*- coding: utf-8 -*-
from collections import OrderedDict
from django.conf.urls import url, include
from rest_framework.schemas import SchemaGenerator
from rest_framework import routers, exceptions
from rest_framework.authtoken import views as authviews
from django.core.urlresolvers import NoReverseMatch
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.views import APIView
from preciosa.api import views


class MyRouter(routers.DefaultRouter):

    def get_api_root_view(self, api_urls=None):
        """
        Es la misma implementacion de la api root view de del
        DefaultRouter, pero con urls nuestras registradas.

        No es muy elegante, pero no encontré otra forma de
        registrar urls propias y las automaticas generadas por el router
        """
        api_root_dict = OrderedDict()
        list_name = self.routes[0].name
        for prefix, viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)

        view_renderers = list(self.root_renderers)
        schema_media_types = []

        if api_urls and self.schema_title:
            view_renderers += list(self.schema_renderers)
            schema_generator = SchemaGenerator(
                title=self.schema_title,
                url=self.schema_url,
                patterns=api_urls
            )
            schema_media_types = [
                renderer.media_type
                for renderer in self.schema_renderers
            ]

        class APIRoot(APIView):
            _ignore_model_permissions = True
            renderer_classes = view_renderers

            def get(self, request, *args, **kwargs):
                if request.accepted_renderer.media_type in schema_media_types:
                    # Return a schema response.
                    schema = schema_generator.get_schema(request)
                    if schema is None:
                        raise exceptions.PermissionDenied()
                    return Response(schema)

                # Return a plain {"name": "hyperlink"} response.
                ret = OrderedDict({
                    'sucursales': reverse('sucursales', request=request),
                    'productos': reverse('productos', request=request),
                    'precios': reverse('precios', request=request),
                    'donde_queda': reverse('donde_queda', request=request),
                    # listar acá otras urls que queremos que aparezcan en
                    # la home de la API
                })
                namespace = request.resolver_match.namespace
                for key, url_name in api_root_dict.items():
                    if namespace:
                        url_name = namespace + ':' + url_name
                    try:
                        ret[key] = reverse(
                            url_name,
                            args=args,
                            kwargs=kwargs,
                            request=request,
                            format=kwargs.get('format', None)
                        )
                    except NoReverseMatch:
                        # Don't bail out if eg. no list routes exist, only detail routes.
                        continue

                return Response(ret)

        return APIRoot.as_view()


router = MyRouter()
router.register(r'cadenas', views.CadenaViewSet)
router.register(r'ciudades', views.CityViewSet)
router.register(r'marcas', views.MarcaViewSet)
router.register(r'fabricantes', views.EmpresaFabricanteViewSet)
router.register(r'categorias', views.CategoriaViewSet)


urlpatterns = [
    url(r"^sucursales/$", views.SucursalesList.as_view(), name='sucursales'),
    url(r"^sucursales/(?P<pk>\d+)$", views.SucursalesList.as_view(),
        name='sucursal_detalle'),
    url(r"^sucursales/(?P<pk>\d+)/productos$",
        views.ProductosList.as_view(),
        name='productos_con_precio_en_sucursal'),
    url(r"^sucursales/(?P<pk_sucursal>\d+)/productos/(?P<pk_producto>\d+)$",
        views.producto_sucursal_detalle,
        name='producto_detalle'),
    url(r"^productos_mejores/(?P<pk_producto>\d+)$",
        views.producto_detalle,
        name='producto_detalle_coor'),
    url(r"^productos/$", views.ProductosList.as_view(), name='productos'),

    url(r"^productos/(?P<pk>\d+)$", views.ProductosList.as_view(), name='productos'),
    url(r"^precios/$", views.PreciosList.as_view(), name='precios'),
    url(r"^utils/donde_queda$", views.donde_queda, name='donde_queda'),

    url(r"^", include(router.urls)),

    url(r'^auth/token$', authviews.obtain_auth_token),
    url(r'^auth/registro$', views.registro, name='registro')
]

preciosa/urls.py
from django.conf import settings
from django.conf.urls import include, url
from precios import views


from accounts.views import SignupView

from django.views.generic.base import RedirectView


from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r'^api/v1/', include("preciosa.api.urls")),  # noqa
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$", SignupView.as_view(
        template_name_email_confirmation_sent='account/email/template_name_email_confirmation_sent')),
    url(r"^account/", include("account.urls")),
    # url(r'^newsletter/', include('newsletter.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^buscador/', views.ProductosSearchAutocomplete.as_view(), name='buscador'),
    url(r'^(\d+)-([a-z0-9-_]+)/$',
        views.ProductosListView.as_view(), name='lista_productos'),
    url(r'^(\d+)-([a-z0-9-_]+)/(?P<pk>\d+)-([a-z0-9-_]+)$',
        views.ProductoDetailView.as_view(),
        name='detalle_producto'),
    url(r'^home/$', RedirectView.as_view(url='/'), name='home'),


    url(r'^blog/', include('radpress.urls')),
    url(r"^voluntarios/", include("preciosa.voluntarios.urls")),
]


if settings.SITE_ID == 3:
    # las crawlers no son bienvenidos en el sitio de desarrollo
    from django.http import HttpResponse
    urlpatterns += [
        url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain"))
    ]
                            

preciosa/voluntarios/urls.py
from django.conf.urls import url
from .views import (CityAutocomplete, dashboard, mapa_categorias, logos, alta_marca, voto_item,
                    alta_cadena_sucursal, autocomplete_nombre_marca, autocomplete_nombre_sucursal,
                    geo_code_data)

urlpatterns = [
    url(r"^$", dashboard, name='voluntarios_dashboard'),      # noqa
    url(r"^mapa_categorias/$", mapa_categorias, name='mapa_categorias'),
    url(r"^logos/$", logos, name='logos'),
    url(r"^logos/marca/(?P<pk>\d+)/paso-(?P<paso>1|2)/$", logos, name='logos_marca'),
    url(r"^marca/$", alta_marca, name='alta_marca'),
    url(r"^marca/autocomplete/nombre/$", autocomplete_nombre_marca,
        name='autocomplete_nombre_marca'),
    url(r"^marca/voto/(?P<pk>\d+)/$", voto_item, name='voto_item'),
    url(r"^sucursal/$", alta_cadena_sucursal, name='alta_cadena_sucursal'),
    url(r"^sucursal/autocomplete/nombre/$", autocomplete_nombre_sucursal,
        name='autocomplete_nombre_sucursal'),
    url(r"^sucursal/voto/(?P<pk>\d+)/$", voto_item, name='voto_item'),
    url(r"^sucursal/geo_code/$", geo_code_data, name='geo_code_data'),
    url(r'^city-autocomplete/$', CityAutocomplete.as_view(), name='city-autocomplete'),
]

preciosa/acuerdos/models.py
# -*- coding: utf-8 -*-
"""
esta app modela el programa Precios Cuidados
ver https://github.com/mgaitan/preciosa/issues/137
"""

from django.db import models
from django.db.models.signals import m2m_changed
from django.db.models import Q



class Region(models.Model):
    """una region incluye provincias y opcionalmente agrega o quita
    algunas ciudades. especificas"""

    nombre = models.CharField(max_length=150)
    provincias = models.ManyToManyField('cities_light.Region',
                                        related_name='incluida_en_region_acuerdo')
    ciudades_incluidas = models.ManyToManyField('cities_light.City',
                                                related_name='incluida_en_region_acuerdo')
    ciudades_excluidas = models.ManyToManyField('cities_light.City',
                                                related_name='excluida_de_region_acuerdo')

    # este campo es una denormalización para simplificar y agilizar queries
    # se actualiza llamando a _calcular_ciudades cuando algunos los otros m2m
    # cambia.
    ciudades = models.ManyToManyField('cities_light.City',
                                      related_name='region_en_acuerdo',
                                      editable=False)

    def __unicode__(self):
        return self.nombre

    def _calcular_ciudades(self):
        """devuelve un QS de ciudades incluyendo todas las ciudades
           que abarca la region. considera provincia, ciudades incluidas y
           excluidas"""
        from cities_light.models import City
        base = City.objects.filter(Q(incluida_en_region_acuerdo=self) |
                                   Q(region__in=self.provincias.all()))
        return base.exclude(Q(excluida_de_region_acuerdo=self))


def actualizar_ciudades_de_region(sender, **kwargs):
    region = kwargs['instance']
    region.ciudades.clear()
    region.ciudades.add(*region._calcular_ciudades())

m2m_changed.connect(actualizar_ciudades_de_region,
                    sender=Region.ciudades_incluidas.through)
m2m_changed.connect(actualizar_ciudades_de_region,
                    sender=Region.ciudades_excluidas.through)
m2m_changed.connect(actualizar_ciudades_de_region,
                    sender=Region.provincias.through)


class Acuerdo(models.Model):
    nombre = models.CharField(max_length=150)
    region = models.ForeignKey(Region)
    sucursales = models.ManyToManyField('precios.Sucursal')
    cadenas = models.ManyToManyField('precios.Cadena')

    def __unicode__(self):
        tipo = 'Cadenas Nacionales' if self.cadenas.exists() else 'Super Regionales'
        return u"%s (%s) - %s" % (self.nombre, self.region, tipo)


class PrecioEnAcuerdoManager(models.Manager):

    def en_acuerdo(self, producto, sucursal):
        """dado un producto y sucursal, devuelve una lista de diccionarios
            con el precio y el nombre del acuerdo"""

        qs = super(PrecioEnAcuerdoManager, self).get_queryset()
        qs = qs.filter(producto=producto)
        # para evitar calcular todo. Si bien hacemos una query mas,
        # el porcentaje de productos bajo acuerdo es muy pequeño
        # la mayoria de las veces no existe.
        if not qs.exists():
            return []

        if sucursal.cadena:
            # grandes cadenas.
            qs = qs.filter(Q(acuerdo__cadenas=sucursal.cadena) |
                           Q(acuerdo__sucursales=sucursal))
        else:
            qs = qs.filter(acuerdo__sucursales=sucursal)

        qs = qs.filter(acuerdo__region__ciudades=sucursal.ciudad).distinct()
        return qs.values('acuerdo__nombre', 'precio')


class PrecioEnAcuerdo(models.Model):
    objects = PrecioEnAcuerdoManager()

    acuerdo = models.ForeignKey(Acuerdo, related_name='precios_en_acuerdo')
    producto = models.ForeignKey('precios.Producto')
    precio = models.DecimalField(max_digits=8, decimal_places=2)

preciosa/api/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class MovilInfo(models.Model):
    """
    ver

    http://docs.phonegap.com/es/1.0.0/phonegap_device_device.md.html
    """
    uuid = models.CharField(max_length=200, primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='movil_info')
    nombre = models.CharField(max_length=200, null=True, blank=True)
    phonegap = models.CharField(max_length=100, null=True, blank=True)
    plataforma = models.CharField(max_length=200, null=True, blank=True)
    plataforma_version = models.CharField(max_length=200, null=True, blank=True)
    preciosa_version = models.CharField(max_length=200, null=True, blank=True)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

preciosa/flatpagex/models.py
from model_utils import Choices
from model_utils.models import TimeStampedModel
from django.db import models
from django.contrib.flatpages.models import FlatPage


class FlatPageX(FlatPage, TimeStampedModel):
    STATUS = Choices('borrador', 'publicado')
    POSICION = Choices(*xrange(11))
    status = models.CharField(choices=STATUS,
                              default=STATUS.borrador,
                              max_length=20)
    posicion = models.PositiveIntegerField(choices=POSICION, default=1)

preciosa/voluntarios/models.py
# -*- coding: utf-8 -*-
"""
en esta aplicacion iran modelos y vistas auxiliares para
realizar tareas de saneamiento de dato masivo basadas
en usuarios voluntarios

la mayoria de los modelos contendran informacion que es
meramente auxiliar y a futuro podra ser eliminada
"""


from django.db import models
from django.contrib.auth.models import User
from model_utils.models import TimeStampedModel

from preciosa.precios.models import (Cadena, Categoria, Marca,
                                    EmpresaFabricante, Sucursal)
from collections import Counter


class MapaCategoria(TimeStampedModel):
    """
    modelo auxiliar para resolver el ticket #64

    guardamos el aporte del usuario y cuando haya suficientes
    eligiremos la combinación origen->destino mas repetida
    """

    origen = models.ForeignKey(Categoria, related_name='mapeo_origen')
    # notar que todas las CAT de origen son depth=2 entonces
    # no hay peligro de colision
    destino = models.ForeignKey(Categoria,
                                related_name='mapeo_destino',
                                verbose_name=u"Yo la asociaría con...",
                                limit_choices_to={'depth': 3})
    user = models.ForeignKey(User, editable=False)
    separar = models.BooleanField(verbose_name=u'Esta lista debería separarse en '
                                               u'varias categorías', default=False)
    comentario = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return u'%s ---> %s' % (self.origen, self.destino)

    class Meta:
        # solo una eleccion por usuario por categoria
        unique_together = ('user', 'origen')

    @classmethod
    def resultados(cls):
        mapa = []
        for origen in Categoria.por_clasificar():
            counter = Counter([voto.destino for voto in
                               cls.objects.filter(origen=origen)])
            mejor_destino = counter.most_common(1)
            mapa.append((origen, mejor_destino))
        return mapa

    @classmethod
    def categorizables_por_voluntario(cls, user):
        ya_hechas = MapaCategoria.objects.filter(user=user).values_list(
            'origen_id', flat=True)
        return Categoria.por_clasificar().exclude(id__in=ya_hechas)


class EntidadCreadaVoluntario(TimeStampedModel):
    user = models.ForeignKey(User, editable=False)

    class Meta:
        abstract = True


class VotoVoluntario(TimeStampedModel):
    user = models.ForeignKey(User, editable=False)
    voto = models.IntegerField()

    class Meta:
        abstract = True


class MarcaEmpresaCreada(EntidadCreadaVoluntario):
    """un modelo para trackear la creacion de marcas
    o empresas por voluntarios"""
    marca = models.ForeignKey(Marca, editable=False, null=True)
    empresa = models.ForeignKey(EmpresaFabricante, editable=False, null=True)


class VotoMarcaEmpresaCreada(VotoVoluntario):
    u"""un usuario vota el item que creó otro """
    item = models.ForeignKey(MarcaEmpresaCreada, related_name='votos')


class SucursalCadenaCreada(EntidadCreadaVoluntario):
    u"""un modelo para trackear la creación de sucursales o cadenas
    de supermercados por voluntarios.

    """
    sucursal = models.ForeignKey(Sucursal, editable=False, null=True)
    cadena = models.ForeignKey(Cadena, editable=False, null=True)


class VotoSucursalCadenaCreada(VotoVoluntario):
    u"""un usuario vota el item que creó otro """
    item = models.ForeignKey(SucursalCadenaCreada, related_name='votos')

preciosa/accounts/forms.py
from django import forms


import account.forms


class SignupForm(account.forms.SignupForm):
    subscribe_to_newsletter = forms.BooleanField(
    	label="Suscribirse al boletin",
        required=False
    )

preciosa/accounts/views.py
from .forms import SignupForm

# from newsletter.models import Subscription, Newsletter

import account.views


class SignupView(account.views.SignupView):
    form_class = SignupForm

    def after_signup(self, form):

        if form.cleaned_data["subscribe_to_newsletter"]:
            pass 

            # if not Subscription.objects.filter(
            #     email_field=form.cleaned_data['email']
            # ).exists():
            #     Subscription.objects.create(
            #         user=self.created_user,
            #         newsletter=Newsletter.objects.first(),
            #         subscribed=True
            #     )
        super(SignupView, self).after_signup(form)

preciosa/acuerdos/views.py
from django.shortcuts import render

# Create your views here.

preciosa/templates/voluntarios/alta_cadena_sucursal.html
{% extends "voluntarios/base.html" %}
{% load bootstrap %}
{% load humanize %}
{% load cropping thumbnail %}

{# pongo los mensajes más cerca del formulario #}
{% block messages %}{% endblock  %}
{% block body %}
    <h1 class="page-header">Agregar sucursal</h1>
     <p class="lead">
        Necesitamos conocer todas las sucursales del país, así podremos
        recibir y enviar precios más precisos.
        Además, nos servirá para hacer estadísticas. Por ejemplo <strong> ¿Cuál cadena de super aumentó más los precios en tu ciudad?</strong>.
    </p>
    <p class="lead">
        Tratá de poner la dirección con precisión y luego, si hacer falta, corregí la ubicación en el mapita.
    </p>
    {% include "_messages.html" %}

<div class="row">
    <div class="col-lg-5">
        {{ form_sucursal.media }}
        <h3>Agregar una nueva sucursal</h3>
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_sucursal|bootstrap }}
            <input class="btn btn-primary btn-lg" type="submit" name="btn_form_sucursal" value="Agregar esta sucursal" />
        </form>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-info">
            <div class="panel-heading">¿No está la cadena de supermercados que buscás?</div>
            <div class="panel-body">
                 <form method="post" action="." enctype="multipart/form-data" >
                     {% csrf_token %}
                     {{ form_cadena|bootstrap }}
                     <input class="btn btn-primary col-lg-12" type="submit" name="btn_form_cadena" value="Agregar" />
                 </form>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="chat-panel panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-comments fa-fw"></i>Votar actividad recientemente
            </div>
            <div class="panel-body">
                <ul class="chat">
                    {% for item in creados %}
                    <li class="left clearfix">
                    <span class="chat-img pull-left">
                        <p>
                        <button title="Parece correcto" class="btn btn-success btn-circle vot_yes" data-pk="{{ item.id }}" type="button">
                            <i class="fa fa-check"></i>
                        </button>
                        </p>
                        <p>
                        <button title="Parece incorrecto" class="btn btn-danger btn-circle vot_no" data-pk="{{ item.id }}" type="button">
                            <i class="fa fa-times"></i>
                        </button>
                        </p>
                    </span>
                    <div class="chat-body clearfix">
                        <div class="header">
                            <strong class="primary-font">{{ item.user.username }} </strong>
                            <small class="pull-right text-muted">
                                <i class="fa fa-clock-o fa-fw"></i> {{ item.created|naturaltime }}
                            </small>
                        </div>
                        <p>
                        {% if item.sucursal %}
                            creó la sucursal <strong>{{ item.sucursal.nombre }}</strong>
                            perteneciente a <strong>{{ item.sucursal.cadena.nombre }}</strong>
                        {% else %}
                            creó la cadena de supermercados
                            <strong>{{ item.cadena.nombre }}</strong>
                        {% endif %}
                        </p>
                    </div>
                    </li>
                    {% endfor %}
                </ul>
           </div><!-- /.panel-body -->
        </div>
    </div>
</div>

{% endblock body %}
{% block extra_footer %}
    <script type="text/javascript">

    $(function(){
        $(document).ready(function(){
            // Make a javascript Autocomplete object and set it up
            var autocomplete2 = $('#id_nombre').yourlabsAutocomplete({
                url: '{% url "autocomplete_nombre_sucursal" %}',
            });

            $('button.vot_yes').on('click', function(){
                var $but = $(this);
                var pk = $but.data('pk');
                $.post('./voto/' + pk + '/',
                       {'voto': true, 'model': 'voluntarios.SucursalCadenaCreada'},
                       function(response){
                           if (response.result){
                               $but.parents('.left').fadeOut();
                           }
                       }
                );
            });

            $('button.vot_no').on('click', function(){
                var $but = $(this);
                var pk = $but.data('pk');
                $.post('./voto/' + pk + '/', {'voto': false, 'model':
                  'voluntarios.SucursalCadenaCreada'}, function(response){
                    if (response.result){
                        $but.parents('.left').fadeOut();
                    }
                });
            });

            $('input[name="direccion"], #id_ciudad').on('change', function(data){
                var url = './geo_code/?ciudad=' + $('#id_ciudad').val() +  '&direccion=' + $('#id_direccion').val();

                var epsg4326 = new OpenLayers.Projection("EPSG:4326");
                var epsg900913 = new OpenLayers.Projection("EPSG:900913");

                var layer = map_ubicacion.map.layers[1];
                // http://jsfiddle.net/_DR_/SMnUJ/
                drag = new OpenLayers.Control.DragFeature(layer, {
                       autoActivate: true,
                });
                map_ubicacion.map.addControl(drag);

                $.get(url, function(data){
                    if (data){

                    var center = new OpenLayers.LonLat(data.lon, data.lat).transform(epsg4326, epsg900913);
                    var point = new OpenLayers.Geometry.Point(center.lon,center.lat);
                    layer.addFeatures([new OpenLayers.Feature.Vector(point)]);
                    if (data.direccion){
                        var zoom = 16;
                    }else{
                        var zoom = 15;
                    }
                    map_ubicacion.map.setCenter(center, 15);
                    }
                });
            });
        });
    });
    </script>
{% endblock extra_footer %}

preciosa/templates/voluntarios/alta_marca.html
{% extends "voluntarios/base.html" %}
{% load bootstrap %}
{% load humanize %}
{% load cropping thumbnail %}


{# pongo los mensajes más cerca del formulario #}
{% block messages %}{% endblock  %}
{% block body %}


    <h1 class="page-header">Agregar marca</h1>


     <p class="lead">
        Saber exáctamente de qué marca es un producto nos va a permitir, en el futuro, hacer estadísticas que nos servirán para comprar mejor. Por ejemplo, <strong> ¿Cuál será la marca que más aumentó los precios en los últimos meses?</strong>.
    </p><p class="lead">

        Para hacer esto, primero necesitamos conocer todas las marcas. Ya conocemos varias, pero seguro vos conocés más.

    </p>


    {% include "_messages.html" %}


<div class="row">

<div class="col-lg-5">
    <h3>Agregar nueva marca</h3>

    <form method="post" id="cropping_form" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form_marca|bootstrap }}

            <input class="btn btn-primary btn-lg" type="submit" value="Agregar esta marca" name="es_marca" />

    </form>

</div>
<div class="col-lg-3">
    <div class="panel panel-info">
                        <div class="panel-heading">
                            ¿No está el fabricante que buscás?
                        </div>
                        <div class="panel-body">
                            <form method="post" action="." >
                            {% csrf_token %}
                            {{ form_empresa|bootstrap }}

                    <input class="btn btn-primary" type="submit" value="Agregar" name="es_empresa" />

                        </form>

                        </div>
                    </div>

</div>
<div class="col-lg-4">

                <div class="chat-panel panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-comments fa-fw"></i>
                            Votar actividad recientemente
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <ul class="chat">
                            {% for item in creados %}
                                <li class="left clearfix">
                                    <span class="chat-img pull-left"><p>
                                    <button title="Parece correcto" class="btn btn-success btn-circle vot_yes" data-pk="{{ item.id }}" type="button"><i class="fa fa-check"></i>
                                    </button></p> <p>
                                    <button title="Parece incorrecto" class="btn btn-danger btn-circle vot_no" data-pk="{{ item.id }}" type="button"><i class="fa fa-times"></i>
                                     </button></p>
                                    </span>

                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">{{ item.user.username }} </strong>
                                            <small class="pull-right text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> {{ item.created|naturaltime }}
                                            </small>
                                        </div>
                                        <p>
                                            {% if item.marca %}
                                            creó la marca <strong>{{ item.marca.nombre }}</strong>
                                            asociada a la empresa <strong>{{ item.marca.fabricante.nombre }}</strong>
                                            {% else %}
                                            creó el fabricante <strong>{{ item.empresa.nombre }}</strong>
                                            {% endif %}
                                        </p>
                                    </div>
                                </li>
                                {% endfor %}

                            </ul>
                        </div>
                        <!-- /.panel-body -->
                    </div>
</div>
</div>


{% endblock body %}


{% block extra_footer %}
    {{ block.super }}

    <script type="text/javascript">

    $(function(){
  // Make a javascript Autocomplete object and set it up
    var autocomplete2 = $('#id_nombre').yourlabsAutocomplete({
        url: '{% url "autocomplete_nombre_marca" %}',
    });

    $('button.vot_yes').on('click', function(){
        var $but = $(this);
        var pk = $but.data('pk');
        $.post('./voto/' + pk + '/', {'voto': true, 'model':
          'voluntarios.MarcaEmpresaCreada'}, function(response){
            if (response.result){
                $but.parents('.left').fadeOut();
            }
        });
    });

    $('button.vot_no').on('click', function(){
        var $but = $(this);
        var pk = $but.data('pk');
        $.post('./voto/' + pk + '/', {'voto': false, 'model':
          'voluntarios.MarcaEmpresaCreada'}, function(response){
            if (response.result){
                $but.parents('.left').fadeOut();
            }
        });
    });


    });

    </script>
{% endblock extra_footer %}

preciosa/templates/voluntarios/autocomplete_nombre_marca.html
{% for marca in marcas %}
    <a class="div choice" href="#">{{ marca.nombre  }}  {% if marca.fabricante %}
        ({{ marca.fabricante.nombre }})
    {% endif %}</a>
{% endfor %}

preciosa/templates/voluntarios/autocomplete_nombre_sucursal.html
{% for sucursal in sucursales %}
<div class="choice">
    {{ sucursal.nombre  }}
    {% if sucursal.cadena %}
        ({{ sucursal.cadena.nombre }})
    {% endif %}
</div>
{% endfor %}

preciosa/templates/voluntarios/mapa_categorias.html
{% extends "voluntarios/base.html" %}
{% load bootstrap %}

{# pongo los mensajes más cerca del formulario #}
{% block messages %}{% endblock  %}
{% block body %}


        <h1 class="page-header">Asociar categorías</h1>


    <p class="lead">Desde esta sección podés ayudar a asociar algunas listas de productos que no estamos seguros en qué categoría poner. Leé las "pistas" que conocemos y elegí la categoría de destino que más te parezca. Cuando haya sufientes coincidencias, moveremos los artículos no clasificados a esa categoría.
     </p>

    <p class="lead">Tomáte tu tiempo, somos muchos y muchas ayudando, y más vale calidad que cantidad.</p>

        {% include "_messages.html" %}



<div class="row">
    <div class="col-lg-3 pull-right">
        {% include "_progress.html" %}
    </div>
    </div>

    <dl>
        <dt>Origen</dt>
        <dd>La lista de origen tiene que ver con <strong>"{{ origen.nombre}}"</strong></dd>
        <dt>Contiene</dt>
        <dd>Algunos de los productos que contiene son:

            <ul>
                {% for producto in productos_ejemplo %}
                    <li>{{ producto.descripcion }}</li>
                {% endfor %}
            </ul>

            </dd>
    </>


    <form action="" method="post">{% csrf_token %}
        {{ form|bootstrap }}
        <input class="btn btn-primary btn-lg" type="submit" value="Me parece que es la mejor opción" />


        <a class="btn btn-default" href="{% url 'mapa_categorias' %}">No tengo idea, paso</a>

    </form>
{% endblock body %}


{% block extra_footer %}
    {{ block.super }}

    <script type="text/javascript">
        var $comment =  $('#id_comentario').parents('.form-group');
        $comment.hide();
        $('#id_separar').on('change', function(){ $comment.toggle() });

    </script>
{% endblock extra_footer %}